version: "3"
services:
  server-1: &server
    platform: linux/amd64
    build:
      context: ./
      dockerfile: dropthebox.dockerfile
    container_name: dtb-server-1
    command: bash -c "./scripts/run_server.sh"
    networks:
      - dtb
    ports:
      - 6900:18216
    volumes:
      - ./src:/code/src
      - ./scripts:/code/scripts
      - ./server_configs.toml:/code/server_configs.toml
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp=unconfined"
    environment:
      DEBUG: true
      PID: 1
        # DEBUG_MEM: true
    stdin_open: true
    tty: true
  server-2: 
    <<: *server
    ports: []
    container_name: dtb-server-2
    environment:
      #DEBUG: true
      PID: 2
  server-3: 
    <<: *server
    container_name: dtb-server-3
    ports: []
    environment:
      # DEBUG: true
      PID: 3
  server-4: 
    <<: *server
    container_name: dtb-server-4
    ports:
      - 6903:12328
    environment:
      # DEBUG: true
      PID: 4
  server-5: 
    <<: *server
    container_name: dtb-server-5
    ports:
      - 6904:13744
    environment:
      # DEBUG: true
      PID: 5

  client-1: &client
    # platform: linux/amd64
    build:
      context: ./
      dockerfile: dropthebox.dockerfile
    command: bash -c "./scripts/run_client.sh claudinoac"
    networks:
      - dtb
    container_name: dtb-client-1
    volumes:
      - ./src:/code/src
      - ./scripts:/code/scripts
      - ./server_configs.toml:/code/server_configs.toml
    environment:
      DEBUG: true
    #  DEBUG_MEM: true
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
  client-2:
    <<: *client
    container_name: dtb-client-2
networks:
  dtb:
    external: true
