version: "3"
services:
  server:
    image: dtb-server
    build:
      context: ./
      dockerfile: dropthebox.dockerfile
    container_name: dtb-server
    command: bash -c "./scripts/run_server.sh"
    networks:
      - dtb
    volumes:
      - ./:/code
      - /code/.git
      - /code/bin
      - ./srv_sync_dir:/code/srv_sync_dir
    # environment:
    #   DEBUG: true
    # DEBUG_MEM: true
    stdin_open: true
    tty: true
  client:
    image: dtb-server
    build:
      context: ./
      dockerfile: dropthebox.dockerfile
    command: bash -c "./scripts/run_client.sh"
    networks:
      - dtb
    volumes:
      - ./:/code
      - /code/.git
      - /code/bin
      - /code/srv_sync_dir
    # environment:
    #   DEBUG: true
        # DEBUG_MEM: true
    stdin_open: true
    tty: true
    deploy:
      replicas: 3
    depends_on:
      - server
networks:
  dtb:
    external: true
