version: "3"
services:
  server-1: &server
      #platform: linux/amd64
    build:
      context: ./
      dockerfile: dropthebox.dockerfile
    container_name: dtb-server-1
    command: bash -c "./scripts/run_server.sh"
    networks:
      - dtb
    ports:
      - 6999
    volumes:
      - ./:/code
      - /code/.git
      - /code/bin
      - ./srv_sync_dir:/code/srv_sync_dir
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp=unconfined"
    environment:
      #DEBUG: true
      PID: 1
        # DEBUG_MEM: true
    stdin_open: true
    tty: true
  server-2: 
    <<: *server
    container_name: dtb-server-2
    environment:
      #DEBUG: true
      PID: 2
  server-3: 
    <<: *server
    container_name: dtb-server-3
    environment:
      DEBUG: true
      PID: 3
  server-4: 
    <<: *server
    container_name: dtb-server-4
    environment:
      # DEBUG: true
      PID: 4
  server-5: 
    <<: *server
    container_name: dtb-server-5
    environment:
      DEBUG: true
      PID: 5

  client:
    # platform: linux/amd64
    build:
      context: ./
      dockerfile: dropthebox.dockerfile
    command: bash -c "./scripts/run_client.sh claudinoac dtb-server-1 6999"
    networks:
      - dtb
    container_name: dtb-client-1
    volumes:
      - ./:/code
      - /code/.git
      - /code/bin
      - /code/srv_sync_dir
    environment:
      DEBUG: true
    #  DEBUG_MEM: true
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
networks:
  dtb:
    external: true
