[server-1]
pid = 1
address = "0.tcp.sa.ngrok.io"
port = 14176
leader = false
base_dir = "/code/srv_sync_dir_1/"

[server-2]
pid = 2
address = "dtb-server-2"
port = 6999
leader = false
base_dir = "/code/srv_sync_dir_2/"

[server-3]
pid = 3
address = "dtb-server-3"
port = 6999
leader = false
base_dir = "/code/srv_sync_dir_3/"

[server-4]
pid = 4
address = "0.tcp.sa.ngrok.io"
port = 10376
leader = false
base_dir = "/code/srv_sync_dir_4/"

[server-5]
pid = 5
address = "0.tcp.sa.ngrok.io"
port = 18833
leader = true
base_dir = "/code/srv_sync_dir_5/"
