var annotated_dup =
[
    [ "ClientContext", "class_client_context.html", "class_client_context" ],
    [ "ClientFileSync", "class_client_file_sync.html", "class_client_file_sync" ],
    [ "ClientPublisher", "class_client_publisher.html", "class_client_publisher" ],
    [ "ClientSession", "class_client_session.html", "class_client_session" ],
    [ "ClientSessionManager", "class_client_session_manager.html", "class_client_session_manager" ],
    [ "ClientSubscriber", "class_client_subscriber.html", "class_client_subscriber" ],
    [ "Command", "class_command.html", "class_command" ],
    [ "Connection", "class_connection.html", "class_connection" ],
    [ "Device", "class_device.html", "class_device" ],
    [ "Event", "class_event.html", "class_event" ],
    [ "FileHandler", "class_file_handler.html", "class_file_handler" ],
    [ "FileMetadata", "class_file_metadata.html", "class_file_metadata" ],
    [ "FileSync", "class_file_sync.html", "class_file_sync" ],
    [ "Packet", "class_packet.html", "class_packet" ],
    [ "ServerContext", "class_server_context.html", "class_server_context" ],
    [ "ServerEventPublisher", "class_server_event_publisher.html", "class_server_event_publisher" ],
    [ "ServerEventSubscriber", "class_server_event_subscriber.html", "class_server_event_subscriber" ],
    [ "Session", "class_session.html", "class_session" ],
    [ "SessionManager", "class_session_manager.html", "class_session_manager" ],
    [ "SessionRequest", "class_session_request.html", "class_session_request" ],
    [ "Socket", "class_socket.html", "class_socket" ],
    [ "UserStore", "class_user_store.html", "class_user_store" ]
];